# Generated by Django 2.2.12 on 2021-02-10 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('gender', models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0, verbose_name='Gender')),
                ('age', models.CharField(default='', max_length=50, verbose_name='Age')),
                ('department', models.CharField(default='', max_length=50, verbose_name='Department')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Admission time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Discharge time')),
                ('description', models.TextField(null=True, verbose_name='Medical history description')),
                ('patient_bed_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bed.Bed')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
