# Generated by Django 2.2.12 on 2021-02-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='科室名称')),
                ('doctor_name', models.CharField(default='', max_length=50, verbose_name='主治医生')),
                ('addr', models.IntegerField(default='', verbose_name='楼层')),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
