# Generated by Django 2.2.12 on 2021-02-08 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(help_text='用户角色标识', max_length=64, unique=True, verbose_name='role code')),
                ('role', models.SmallIntegerField(choices=[(0, '医生'), (1, '护士'), (2, '护士长')], default=0, verbose_name='角色')),
                ('permission', models.CharField(choices=[('VISITOR', '普通用户'), ('UPDATE', '修改权限'), ('DELETE', '删除用户'), ('ADD', '新增用户'), ('ADMIN', '管理员权限')], default='VISITOR', max_length=50, verbose_name='权限')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='用户id', unique=True, verbose_name='user id')),
                ('role_codes', models.CharField(blank=True, default=None, help_text='用户的角色codes', max_length=256, verbose_name='role codes')),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('password', models.CharField(default='123', max_length=50, verbose_name='密码')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机')),
                ('position', models.CharField(default='', max_length=50, verbose_name='职位')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('description', models.TextField(null=True, verbose_name='个人描述')),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(help_text='用户角色标识', max_length=64, verbose_name='role code')),
                ('pms_code', models.CharField(help_text='权限code', max_length=64, verbose_name='permission code')),
            ],
            options={
                'db_table': 'role_permission',
                'unique_together': {('role_code', 'pms_code')},
            },
        ),
    ]
