# Generated by Django 2.2.2 on 2022-03-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_name',
            field=models.CharField(max_length=70, verbose_name='Bed number'),
        ),
    ]
